重定向过时的标签,清理不存在的标签
EhTagTranslation/Database pull request #108
Opened 2022-02-23 13:23 UTC by xioxin

2022-02-24 03:46 UTC, xioxin commented
@OpportunityLiu 这个最好看一眼，尤其是删掉的标签。是与E站标签数据进行匹配的到的。如果需要完整的标签数据我可以私发你。

2022-02-24 06:41 UTC, OpportunityLiu commented
你的注释都没对应到行上，我没法看啊。。。

male 和 female 空间里没有的标签就先保留吧，理论上存在，只是现在没有对应的本子

2022-02-24 07:15 UTC, xioxin commented
> 你的注释都没对应到行上，我没法看啊。。。
> 
> male 和 female 空间里没有的标签就先保留吧，理论上存在，只是现在没有对应的本子

通过提交查看，PR这里不知道为啥不现实
https://github.com/EhTagTranslation/Database/commit/cca84bc63ca2088bf737771181e154c8f4a7a1e9

2022-02-24 07:32 UTC, xioxin commented
male 里有很多看起来从 female 中拷贝过来的，比如男性里面有阴道破坏。

2022-02-24 13:36 UTC, OpportunityLiu commented
> male 里有很多看起来从 female 中拷贝过来的，比如男性里面有阴道破坏。

理论上有的，futanari 比 otokufutanari 流行太多了

2022-02-24 13:46 UTC, OpportunityLiu commented
其他命名空间的没啥问题

2022-02-24 14:10 UTC, xioxin commented
> > male 里有很多看起来从 female 中拷贝过来的，比如男性里面有阴道破坏。
> 
> 理论上有的，futanari 比 otokufutanari 流行太多了

我是遍历 https://repo.e-hentai.org/tools.php?act=taggroup&mastertag=10000 接口, 把所有的标签爬出来的, 确定这些标签不存在. 
我觉得女性下面的动物相关还原回去,这些还是有可能出现的.
男性那边确实都比较离谱我还是倾向移除掉.

2022-02-25 02:16 UTC, OpportunityLiu requested changes

2022-02-25 02:16 UTC, OpportunityLiu commented on database/female.md
> -| steward | 男空乘服 | 在公共汽车，电梯或飞机上工作的人的制服。需要`crossdressing`标签。 |  |
这类的也留着吧

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| shapening | 平面化 | 参与者弄平，融化或以其他方式变为几何形状（例如球形或立方体）。不要与`body modification`相混淆。 |  |
+1

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| wingjob | 翼交 | 用翅膀模拟性器官。 |  |
+1

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| albino | 白化 | 红眼和颜色极浅的皮肤。 |  |
+1

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| cockslapping | 屌掴 | 用阴茎打人（通常是脸）。 |  |
+1

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| headless | 无头 | 没有头的生物，不包括参与者被斩首的情况。 |  |
+1

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| adventitious mouth | 畸位口 | 在身体的意想不到的地方至少有一个嘴（例如手、躯干或尾巴）。 |  |
+1

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| bandaid | 创可贴 | 创可贴位于阴部或乳头上。 |  |
+1

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| haigure | 高叉装 | 穿着在胳膊和腿部弯曲的紧身衣服的女孩，强调阴部的位置。 |  |
+1

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| hijab | 头巾 | 一个覆盖头部和胸部的面纱，主要用于遮盖头发。需要`crossdressing`标签。 |  |
+1

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| sarashi | 缠胸布 | 缠胸布（日语：晒/さらし），围绕胃/胸部区域的长绷带状布料。对于男性来说，它通常覆盖胃部。需要`bandages`标签。 |  |
+1

2022-02-25 02:16 UTC, OpportunityLiu commented on database/male.md
> -| unusual insertions | 异物插入 | 将通常不用于性活动或医学检查的无生命物体插入生殖器或肛门的行为。需要`sex toys`标签。 |  |
+1

2022-02-25 02:20 UTC, closed without merging

2022-02-25 02:56 UTC, xioxin commented
我花了3天时间整理检查这些数据，每个问题标签都进行了单独的检查，确保没有问题。
我甚至确认了 cockslapping 标签是要添加到被打的性别一方的，才确定男性中应该被移除。
我仍然坚持移除掉不存在的标签，在需要的时候再添加。

我觉得在这个观点上很难达成一致，我也浪费了太多时间，我不希望在这个事情上继续消耗时间了。
但我觉得重定向过时标签还是很有意义的，如果你们愿意继续跟进这个事情，请重新打开PR并根据自己的意愿调整，分支我不会删掉，如果觉得整个事情没有意义可以移除掉cleaning分支。

2022-07-26 04:11 UTC, OpportunityLiu commented
https://github.com/EhTagTranslation/Database/actions/workflows/check_tags.yml

加上了检查，现在可以每周检查需要添加的标签了，就把不存在的标签移除了