添加 detached sleeves 新标签
EhTagTranslation/Database pull request #129
Opened 2022-05-24 03:54 UTC by oliver-zhq

https://ehwiki.org/wiki/detached_sleeves

edit：
添加 detached sleeves ，代表角色甘雨，初音未来，博丽灵梦。

---

2022-05-24 04:31 UTC, OpportunityLiu requested changes

2022-05-24 04:31 UTC, OpportunityLiu commented on database/female.md
> +| detached sleeves | 分离袖子 | 一种上衣没有肩部分，袖子与衣服主体分离同时不以手套样式穿着的服饰。不应与`gloves`混淆。<br>![图](%22https://ehgt.org/7f/0e/7f0ee9e9b54ca575c57b63befd627d7aaa93dd43-1791186-1213-1865-png_l.jpg%22) | [萌娘百科](%22http
这链接都有问题啊 前后的 `%22` 应删去

2022-05-24 09:01 UTC, oliver-zhq commented
%22 是Actions让加上的，不加上过不了检查

2022-05-24 13:03 UTC, OpportunityLiu commented
为啥要用引号呢？ Actions 只是检查语法，你用引号语法都不对，换成 `%22` 链接无法访问

图片的语法是 `![](url)`，超链接的语法是 `[text](url)` 都不需要引号的

R18 图用 `![](# "url")`，前面有个 `#`

文档里都有写的 https://github.com/EhTagTranslation/Database/wiki/%E5%8F%82%E4%B8%8E%E7%BF%BB%E8%AF%91#markdown-%E4%B9%A6%E5%86%99%E6%8C%87%E5%BC%95

2022-05-24 14:21 UTC, oliver-zhq commented
添加 detached sleeves 新标签

2022-05-24 14:23 UTC, oliver-zhq commented
添加 detached sleeves 新标签

2022-05-24 14:43 UTC, OpportunityLiu approved these changes

2022-05-24 14:44 UTC, merged

2022-06-18 16:31 UTC, oliver-zhq commented
> https://github.com/EhTagTranslation/Database/wiki/%E5%8F%82%E4%B8%8E%E7%BF%BB%E8%AF%91
> 
> @oliver-zhq 还是请你仔细看一下。。。最近提交的标签质量有点低

具体哪里有问题请指出来。

2022-06-18 16:59 UTC, OpportunityLiu commented
7a06f4d4b7dec9b09dd3cf923ba2679fd598821d f9c19c58ba5157e96e30e210a0f3ef4d22bb7cb4 42cb518761f05fbe750eb010d161d655e6b99d31 76229b7540f779d35ba0396e877ebb8f39b54650 e20e449ddcd1f9153a4f0c9d03282941aec4f629 1d8eb230a599529a7d24832abc820f84634dd7be

> 同一实质作品、人物有官方别名时，或同一作者以多个名义活动时，优先保留最常用名称，其他别名（名义）写在括号内，如 五更琉璃（黑猫）、甘诘留太（A・浪漫・我慢）。（全角括号 （））
> #44

2022-06-18 17:06 UTC, oliver-zhq commented
> [7a06f4d](https://github.com/EhTagTranslation/Database/commit/7a06f4d4b7dec9b09dd3cf923ba2679fd598821d) [f9c19c5](https://github.com/EhTagTranslation/Database/commit/f9c19c58ba5157e96e30e210a0f3ef4d22bb7cb4) [42cb518](https://github.com/EhTagTranslation/Database/commit/42cb518761f05fbe750eb010d161d655e6b99d31) [76229b7](https://github.com/EhTagTranslation/Database/commit/76229b7540f779d35ba0396e877ebb8f39b54650) [e20e449](https://github.com/EhTagTranslation/Database/commit/e20e449ddcd1f9153a4f0c9d03282941aec4f629) [1d8eb23](https://github.com/EhTagTranslation/Database/commit/1d8eb230a599529a7d24832abc820f84634dd7be)
> 
> > 同一实质作品、人物有官方别名时，或同一作者以多个名义活动时，优先保留最常用名称，其他别名（名义）写在括号内，如 五更琉璃（黑猫）、甘诘留太（A・浪漫・我慢）。（全角括号 （））
> > #44

hololive的几个标签是因为没有官方中文名称，但是民间认可了。

2022-06-18 17:16 UTC, OpportunityLiu commented
你只能选一个，另一个写在描述里

2022-06-18 17:17 UTC, oliver-zhq commented
> > [7a06f4d](https://github.com/EhTagTranslation/Database/commit/7a06f4d4b7dec9b09dd3cf923ba2679fd598821d) [f9c19c5](https://github.com/EhTagTranslation/Database/commit/f9c19c58ba5157e96e30e210a0f3ef4d22bb7cb4) [42cb518](https://github.com/EhTagTranslation/Database/commit/42cb518761f05fbe750eb010d161d655e6b99d31) [76229b7](https://github.com/EhTagTranslation/Database/commit/76229b7540f779d35ba0396e877ebb8f39b54650) [e20e449](https://github.com/EhTagTranslation/Database/commit/e20e449ddcd1f9153a4f0c9d03282941aec4f629) [1d8eb23](https://github.com/EhTagTranslation/Database/commit/1d8eb230a599529a7d24832abc820f84634dd7be)
> > > 同一实质作品、人物有官方别名时，或同一作者以多个名义活动时，优先保留最常用名称，其他别名（名义）写在括号内，如 五更琉璃（黑猫）、甘诘留太（A・浪漫・我慢）。（全角括号 （））
> > > #44
> 
> hololive的几个标签是因为没有官方中文名称，但是民间认可了。



> 你只能选一个，另一个写在描述里

好